### ISSUE TITLE
install org-webhook fails when webhook already exists

### ISSUE THREAD

**Issue by tanya-coding** [atomist/rug-functions-github#20]
@tanya-coding commented on [Tue Aug 01 2017](https://github.com/atomist/github-rugs/issues/64)

It used to return a user friendly error message but now it returns a generic failure.

https://app.logz.io/#/dashboard/kibana?kibanaRoute=%2Fdoc%2F%5BlogzioCustomerIndex%5DYYMMDD%2FlogzioCustomerIndex170801_v2%2Fhttp-bulk%2F%3Fid%3DAV2eq-D_ycpQeAB8vCav

---

@tanya-coding commented on [Tue Aug 01 2017](https://github.com/atomist/github-rugs/issues/64#issuecomment-319428704)

cc: @cdupuis This might belong in rug-runner?

---

@cdupuis commented on [Tue Aug 01 2017](https://github.com/atomist/github-rugs/issues/64#issuecomment-319429043)

Unlikely as the rug returns `failed` rug-runner is sending the generic error.

---

@cdupuis commented on [Tue Aug 01 2017](https://github.com/atomist/github-rugs/issues/64#issuecomment-319429343)

Also `Invalid JSON: <json>:1:0 Expected json literal but found H\nHTTP/1.1 422 Unprocessable Entity\n^ in .atomist/handlers/utils/Slack.js at line number 1`

---

@tanya-coding commented on [Fri Aug 11 2017](https://github.com/atomist/github-rugs/issues/64#issuecomment-321823099)

Instead of an error message we should show a warning similar to:

![image](https://user-images.githubusercontent.com/19268924/29216630-e4e208f4-7e74-11e7-8f35-de1a1d36aca6.png)

**Comment by alankstewart** [comment]
Changes in #21 in artifact-source have returned to prior working behaviour when the github-api lib was being used. GitHub error message can now be deserialised by github-rugs as before
