### ISSUE TITLE
Request for a Feature to allow to specify Pull Request merge method

### ISSUE THREAD

**Issue by zetaron** [atomist/rug-functions-github#26]
GitHub currently provides three methods to merge a PR:
- merge: Add all commits from the head branch to the base branch with a merge commit.
- squash: Combine all commits from the head branch into a single commit in the base branch.
- rebase: Add all commits from the head branch onto the base branch individually.

For our Repositories we like to use the rebase method, which currently is not supported due to the hardcoded nature of the `merge-github-pull-request` Rug Function.

https://github.com/atomist/rug-functions-github/blob/138591b801e5d0eafa012c78dfba8278836571ca/src/main/scala/com/atomist/rug/function/github/pullrequest/MergePullRequestFunction.scala#L18-L31

I'd propose to add a new Parameter which carries the merge method with a fallback to `merge`.
This would allow the caller to specify how it wants to merge, which in turn would allow for the Slack integration to eg. provide buttons for all three or only the configured merge methods.

**Comment by ddgenome** [comment]
Thanks for using Atomist @zetaron! This is definitely something we want to do. Allowing the rebase option will be more straightforward than the squash and merge, which if done properly requires a concatenation of all the merged commit messages.

**Comment by alankstewart** [comment]
@zetaron Added `mergeMethod` to invoke signature as suggested and in the case of squash, the commit message is a concatenation of all the commits for the PR, separated by a new line.

**Comment by alankstewart** [comment]
@zetaron Currently in our Slack staging environment, one can set the mergeMethod parameter to override the default of "merge" with `set mergeMethod rebase`, for example, but more work is required to change this to buttons or adding a new text box to enter the required method

**Comment by zetaron** [comment]
@alankstewart how exactly would I do that?
Assume I'm in a slack channel which is observed by atomist how would I tell it to use rebase?

**Comment by alankstewart** [comment]
@zetaron This will be improved, but if the current code goes to production, you can set a parameter (as with any param) with `set <param> <value>' See example image attached
<img width="463" alt="screen shot 2017-09-08 at 5 28 47 pm" src="https://user-images.githubusercontent.com/1015790/30200770-a72c93be-94bb-11e7-8efb-e8b8b3fc9226.png">

**Comment by zetaron** [comment]
Thanks I wasn't aware that it was possible to configure parameters this way :)

@alankstewart Should this issue be closed or stay open until it reaches production?

**Comment by alankstewart** [comment]
Yes, I could have modified any of the parameters shown, for example, `set repo comfoobar`.
Let's leave it open till we can improve the Slack user experience better.

**Comment by ddgenome** [comment]
@alankstewart it looks like the default value for the mergeMethod parameter does not work. Production has picked up the latest version of rug-functions-github and we are seeing this:

```
09/11 20:04:37.106 [command-handler-pool-5] WARN  [ba62dac5-eb34-4f5f-bfc8-ad4e6fd837bc] c.a.r.r.i.o.CommandHandlerInvoker - Rug Function merge-github-pull-request threw exception: Parameter 'mergeMethod' not found: Had ArraySeq(SimpleParameterValue(issue,13), SimpleParam
eterValue(repo,sylvain-test4), SimpleParameterValue(owner,atomisthqa), SimpleParameterValue(apiUrl,https://api.github.com/), SimpleParameterValue(corrid,ba62dac5-eb34-4f5f-bfc8-ad4e6fd837bc), SimpleParameterValue(user_token,57d924a624d552e5ee29efa293e64ffa9795ac73))
java.lang.IllegalArgumentException: Parameter 'mergeMethod' not found: Had ArraySeq(SimpleParameterValue(issue,13), SimpleParameterValue(repo,sylvain-test4), SimpleParameterValue(owner,atomisthqa), SimpleParameterValue(apiUrl,https://api.github.com/), SimpleParameterValue
(corrid,ba62dac5-eb34-4f5f-bfc8-ad4e6fd837bc), SimpleParameterValue(user_token,57d924a624d552e5ee29efa293e64ffa9795ac73))
```

**Comment by ddgenome** [comment]
@alankstewart it looks like the default value for `mergeMethod` is not working, we are seeing this in the logs:

```
09/11 20:04:37.106 [command-handler-pool-5] WARN  [ba62dac5-eb34-4f5f-bfc8-ad4e6fd837bc] c.a.r.r.i.o.CommandHandlerInvoker - Rug Function merge-github-pull-request threw exception: Parameter 'mergeMethod' not found:...
```

**Comment by ddgenome** [comment]
PRs that pass all checks will now have three buttons: Merge, Squash & Merge, and Rebase & Merge. Thanks for the request!
